# -*- coding: utf-8 -*-
"""chatbot_tester

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDW1Pz3hCpzXkxxI22m5MSP_VhoO8IFE
"""

# COMPONENT 4: TESTING SUITE & PERFORMANCE METRICS

import time
from collections import defaultdict

class ChatbotTester:
    """Test and measure chatbot performance"""

    def __init__(self, chatbot):
        self.chatbot = chatbot
        self.test_results = []

    def run_test_suite(self, test_cases):
        """Run comprehensive tests"""

        results = {
            'total_tests': 0,
            'correct_intent': 0,
            'response_times': [],
            'intent_accuracy': {},
            'escalations': 0,
            'test_details': []
        }

        for i, test in enumerate(test_cases, 1):
            query = test['query']
            expected_intent = test['expected_intent']

            # Measure response time (in milliseconds for better precision)
            start_time = time.perf_counter()
            result = self.chatbot.generate_response(query)
            end_time = time.perf_counter()
            response_time = (end_time - start_time) * 1000  # Convert to milliseconds

            # Check if intent matches
            intent_correct = (result['intent'] == expected_intent)

            # Store results
            results['total_tests'] += 1
            results['response_times'].append(response_time)

            if intent_correct:
                results['correct_intent'] += 1

            if result['should_escalate']:
                results['escalations'] += 1

            # Track per-intent accuracy
            if expected_intent not in results['intent_accuracy']:
                results['intent_accuracy'][expected_intent] = {'correct': 0, 'total': 0}

            results['intent_accuracy'][expected_intent]['total'] += 1
            if intent_correct:
                results['intent_accuracy'][expected_intent]['correct'] += 1

            # Store detailed result
            results['test_details'].append({
                'query': query,
                'expected_intent': expected_intent,
                'detected_intent': result['intent'],
                'correct': intent_correct,
                'confidence': result['confidence'],
                'response_time': response_time,
                'escalated': result['should_escalate']
            })

            # Print progress
            status = "YES" if intent_correct else "NO"
            print(f"{status} Test {i}/{len(test_cases)}: {query[:50]}... -> {result['intent']}")

            # Add a small delay to avoid hitting rate limits
            time.sleep(0.5)

        return results

    def calculate_metrics(self, results):
        """Calculate performance metrics"""

        metrics = {}

        # Overall accuracy
        metrics['intent_accuracy'] = (results['correct_intent'] / results['total_tests']) * 100

        # Average response time
        metrics['avg_response_time'] = sum(results['response_times']) / len(results['response_times'])
        metrics['max_response_time'] = max(results['response_times'])
        metrics['min_response_time'] = min(results['response_times'])

        # Per-intent accuracy
        metrics['per_intent_accuracy'] = {}
        for intent, data in results['intent_accuracy'].items():
            accuracy = (data['correct'] / data['total']) * 100
            metrics['per_intent_accuracy'][intent] = accuracy

        # Escalation rate
        metrics['escalation_rate'] = (results['escalations'] / results['total_tests']) * 100

        # Task completion rate (simulated based on intent accuracy)
        metrics['task_completion_rate'] = metrics['intent_accuracy']

        return metrics

    def generate_report(self, results, metrics):
        """Generate comprehensive test report"""

        print(f"\nPERFORMANCE METRICS REPORT")

        print(f"\n OVERALL PERFORMANCE")
        print(f"Total Test Cases: {results['total_tests']}")
        print(f"Intent Classification Accuracy: {metrics['intent_accuracy']:.1f}%")
        print(f"Task Completion Rate: {metrics['task_completion_rate']:.1f}%")
        print(f"Escalation Rate: {metrics['escalation_rate']:.1f}%")

        print(f"\n  RESPONSE TIME")
        print(f"Average: {metrics['avg_response_time']:.2f} ms")
        print(f"Min: {metrics['min_response_time']:.2f} ms")
        print(f"Max: {metrics['max_response_time']:.2f} ms")

        print(f"\n PER-INTENT ACCURACY")
        for intent, accuracy in sorted(metrics['per_intent_accuracy'].items()):
            bar = "-" * int(accuracy / 5)
            print(f"{intent:25} {accuracy:5.1f}% {bar}")

        print(f"\n FAILED TESTS")
        failed_tests = [t for t in results['test_details'] if not t['correct']]
        if failed_tests:
            for test in failed_tests:
                print(f"Query: {test['query']}")
                print(f"  Expected: {test['expected_intent']}")
                print(f"  Got: {test['detected_intent']}")
                print()
        else:
            print("All tests passed!")

        return {
            'results': results,
            'metrics': metrics
        }

# Initialize tester
tester = ChatbotTester(gemini_chatbot)

# RUN COMPREHENSIVE TESTS

# Define test cases with expected intents
test_cases = [
    # Product search tests
    {'query': 'Show me red dresses', 'expected_intent': 'product_search'},
    {'query': 'Do you have blue jeans?', 'expected_intent': 'product_search'},
    {'query': 'Looking for boots', 'expected_intent': 'product_search'},

    # Product details
    {'query': 'What sizes does this come in?', 'expected_intent': 'product_details'},
    {'query': 'What colors are available?', 'expected_intent': 'product_details'},

    # Order tracking
    {'query': 'Where is my order ORD001?', 'expected_intent': 'order_tracking'},
    {'query': 'When will my package arrive?', 'expected_intent': 'order_tracking'},

    # Order status
    {'query': 'What is my order status?', 'expected_intent': 'order_status'},

    # Returns
    {'query': 'How do I return this item?', 'expected_intent': 'returns_exchanges'},
    {'query': 'What is your return policy?', 'expected_intent': 'returns_exchanges'},

    # Refund
    {'query': 'I want a refund', 'expected_intent': 'refund_request'},
    {'query': 'How long does refund take?', 'expected_intent': 'refund_request'},

    # Account
    {'query': 'I forgot my password', 'expected_intent': 'account_management'},
    {'query': 'Cannot login to my account', 'expected_intent': 'account_management'},

    # Contact
    {'query': 'What is your phone number?', 'expected_intent': 'contact_info'},
    {'query': 'What are your business hours?', 'expected_intent': 'contact_info'},

    # Payment/shipping
    {'query': 'What payment methods do you accept?', 'expected_intent': 'payment_shipping'},
    {'query': 'How much is shipping?', 'expected_intent': 'payment_shipping'},

    # Size guide
    {'query': 'What size should I get?', 'expected_intent': 'size_guide'},
    {'query': 'Do these run large or small?', 'expected_intent': 'size_guide'},

    # General FAQ (
    {'query': 'Do you have physical stores?', 'expected_intent': 'general_faq'},

    # Escalation
    {'query': 'I want to speak to a manager', 'expected_intent': 'escalation'},
    {'query': 'Connect me to a human', 'expected_intent': 'escalation'},
]

print(f"Total test cases: {len(test_cases)}")

# Run tests
results = tester.run_test_suite(test_cases)

# Calculate metrics
metrics = tester.calculate_metrics(results)

# Generate report
report = tester.generate_report(results, metrics)

print(f"\nOverall Accuracy: {metrics['intent_accuracy']:.1f}%")