# -*- coding: utf-8 -*-
"""intent_classifier.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yxi27k525CWNB0cpBZKP9brMTlD-Uqe_
"""

# Install required packages
!pip install -q datasets transformers huggingface-hub pandas matplotlib

# Install Gemini API
!pip install -q google-generativeai

import time
import google.generativeai as genai
from google.colab import userdata
import os

os.environ["HUGGINGFACEHUB_API_TOKEN"] = userdata.get('HF_TOKEN')

# API key
GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')
genai.configure(api_key=GEMINI_API_KEY)

from datasets import load_dataset
import pandas as pd

# Load dataset
dataset = load_dataset("bitext/Bitext-customer-support-llm-chatbot-training-dataset")

# Show first 5 examples
print("SAMPLE EXAMPLES FROM DATASET:")

for i in range(5):
    example = dataset['train'][i]
    print(f"\n Example {i+1}:")
    print(f"   User: {example['instruction']}")
    print(f"   Bot: {example['response'][:120]}...")
    if 'category' in example:
        print(f"   Category: {example['category']}")

# Analyze categories
df = pd.DataFrame(dataset['train'])

print(f"\nDATASET ANALYSIS:")
print(f"Total rows: {len(df)}")
print(f"Columns: {df.columns.tolist()}")

if 'category' in df.columns:
    print(f"\n Unique categories: {df['category'].nunique()}")
    print("\n Top 11 Categories:")
    print(df['category'].value_counts().head(11))

# Deep dive into categories
print("DETAILED CATEGORY ANALYSIS\n")

if 'category' in df.columns:
    categories = df['category'].value_counts()

# Sample queries from each major category
print("\nSAMPLE QUERIES BY CATEGORY:")

# Get top 8 categories
top_categories = categories.head(8).index

for category in top_categories:
    print(f"\n Category: {category}")

    # Get 3 example queries from this category
    examples = df[df['category'] == category].head(3)

    for idx, row in examples.iterrows():
        print(f"   - {row['instruction']}")

# COMPONENT 1: INTENT CLASSIFIER

class IntentClassifier:
    """Rule-based intent classifier with improved keyword matching"""

    def __init__(self):
        """Initialize with enhanced intent patterns"""

        # Enhanced keywords for each intent
        self.intent_patterns = {
            'product_search': {
                'keywords': ['show', 'find', 'looking for', 'need', 'want', 'browse', 'search',
                           'do you have', 'any', 'sell', 'available products', 'see', 'view'],
                'priority': 1
            },
            'product_details': {
                'keywords': ['what size', 'what color', 'colors available', 'sizes available',
                           'material', 'fabric', 'made of', 'features', 'details about',
                           'machine washable', 'washable', 'care instructions'],
                'priority': 2
            },
            'order_tracking': {
                'keywords': ['track', 'where is my order', 'delivery', 'shipped', 'shipping status',
                           'when will arrive', 'tracking number', 'package arrive', 'my package'],
                'priority': 2
            },
            'order_status': {
                'keywords': ['order status', 'order history', 'my orders', 'past orders',
                           'view order', 'order details', 'show me my order'],
                'priority': 2
            },
            'returns_exchanges': {
                'keywords': ['return', 'exchange', 'send back', 'not satisfied', 'wrong item',
                           'return policy', 'how to return', 'exchange for', 'want to exchange'],
                'priority': 2
            },
            'refund_request': {
                'keywords': ['refund', 'money back', 'get my money', 'reimburs', 'charged wrong',
                           'want refund', 'refund policy', 'want a refund', 'need a refund'],
                'priority': 3  # High priority for refund
            },
            'account_management': {
                'keywords': ['password', 'login', 'account', 'sign in', 'register', 'forgot password',
                           'cant login', 'access account', 'update email', 'change email',
                           'update my email', 'account settings'],
                'priority': 2
            },
            'contact_info': {
                'keywords': ['phone number', 'email address', 'reach you', 'customer service number',
                           'support number', 'call you', 'contact you', 'business hours',
                           'what are your hours', 'when are you open', 'contact support'],
                'priority': 2
            },
            'payment_shipping': {
                'keywords': ['payment', 'pay', 'shipping cost', 'delivery fee', 'how much',
                           'payment methods', 'credit card', 'shipping price', 'free shipping',
                           'offer free shipping', 'shipping fee'],
                'priority': 2
            },
            'size_guide': {
                'keywords': ['size chart', 'fit', 'runs large', 'runs small', 'sizing',
                           'what size should', 'size guide', 'measurements', 'run large',
                           'run small', 'true to size'],
                'priority': 3  # High priority for size questions
            },
            'general_faq': {
                'keywords': ['store location', 'physical store', 'sale', 'discount',
                             'countries', 'ship to', 'stores', 'have stores', 'brick and mortar',
                             'retail location', 'visit store'],
                'priority': 2
            },
            'escalation': {
                'keywords': ['manager', 'human', 'agent', 'real person', 'speak to someone',
                           'not helping', 'frustrated', 'angry', 'complaint', 'speak to a',
                           'talk to a', 'connect me to'],
                'priority': 4  # Highest priority
            }
        }

    def classify(self, query):
        """Classify user query into intent"""
        query_lower = query.lower()

        # Score each intent
        scores = {}
        for intent, data in self.intent_patterns.items():
            keywords = data['keywords']
            priority = data['priority']

            # Count keyword matches
            matches = sum(1 for keyword in keywords if keyword in query_lower)

            if matches > 0:
                # Score = matches * priority weight
                scores[intent] = matches * (1 + priority)

        # Return intent with highest score, or default
        if scores:
            best_intent = max(scores, key=scores.get)
            return best_intent

        return 'general_faq'

    def classify_with_confidence(self, query):
        """Classify and return confidence score"""
        query_lower = query.lower()
        scores = {}

        for intent, data in self.intent_patterns.items():
            keywords = data['keywords']
            priority = data['priority']
            matches = sum(1 for keyword in keywords if keyword in query_lower)
            if matches > 0:
                scores[intent] = matches * (1 + priority)

        if scores:
            best_intent = max(scores, key=scores.get)
            total_score = sum(scores.values())
            confidence = scores[best_intent] / total_score
            return best_intent, confidence

        return 'general_faq'

        # TEST INTENT CLASSIFIER

# Create classifier instance
classifier = IntentClassifier()

# Test queries
test_cases = [
    "Show me red dresses under $50",
    "Where is my order ORD001?",
    "I want to return this item",
    "What sizes do you have for this dress?",
    "I need a refund for my order",
    "I forgot my password",
    "What is your phone number?",
    "I want to speak to a manager NOW",
    "Do you have blue jeans in stock?",
    "How much is shipping to California?",
    "What size should I get? I'm usually a medium",
    "Are you having any sales right now?",
    "Do you have physical stores?"

]

results = []

for query in test_cases:
    intent, confidence = classifier.classify_with_confidence(query)
    results.append({
        'query': query,
        'intent': intent,
        'confidence': confidence
    })

    print(f"\nQuery: {query}")
    print(f"   -> Intent: {intent}")
    print(f"   -> Confidence: {confidence:.2%}")

print(f"\nTested {len(test_cases)} queries successfully!")