# -*- coding: utf-8 -*-
"""prompt_templates

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLTfZV2WfEfDB6JINEWDmG0JLoIA5Pwf
"""

# COMPONENT 2: PROMPT TEMPLATES
# Different prompts for different intents

class PromptTemplates:
    """Collection of prompt templates for different scenarios"""

    def __init__(self):
        """Initialize all prompt templates"""
        pass

    def get_product_search_prompt(self, user_query, products):
        """
        Prompt for product recommendations

        Args:
            user_query: User's search query
            products: List of matching products (dicts)
        """

        # Format products into readable text
        if not products or len(products) == 0:
            return self.get_no_products_prompt(user_query)

        product_list = ""
        for i, prod in enumerate(products, 1):
            product_list += f"\n{i}. {prod['name']} - ${prod['price']}"
            product_list += f"\n   Available in: {', '.join(prod.get('colors', ['Multiple colors']))}"
            product_list += f"\n   Sizes: {', '.join(prod.get('sizes', ['Multiple sizes']))}"
            product_list += f"\n   {prod.get('description', '')}\n"

        prompt = f"""You are a friendly and enthusiastic fashion shopping assistant.

Customer asked: "{user_query}"

Here are the products we have:
{product_list}

Instructions:
- Recommend these products naturally and enthusiastically
- Mention key features (price, colors, sizes)
- Be conversational, not robotic
- Keep response under 150 words
- End with: "Would you like more details about any of these?"

Your response:"""

        return prompt

    def get_no_products_prompt(self, user_query):
        """Prompt when no products found"""

        prompt = f"""You are a helpful fashion shopping assistant.

Customer asked: "{user_query}"

Unfortunately, we don't have products matching that exact request right now.

Instructions:
- Apologize politely
- Suggest they try a different search or browse categories
- Offer to help them find something similar
- Keep it friendly and helpful
- Keep response under 80 words

Your response:"""

        return prompt

    def get_order_tracking_prompt(self, order_info):
        """Prompt for order tracking responses"""

        prompt = f"""You are a helpful customer service assistant.

Order Information:
- Order ID: {order_info.get('order_id', 'N/A')}
- Status: {order_info.get('status', 'Unknown')}
- Order Date: {order_info.get('order_date', 'N/A')}
- Tracking Number: {order_info.get('tracking_number', 'Not yet assigned')}

Instructions:
- Provide the order status clearly
- Be professional and reassuring
- If shipped, mention tracking number
- If processing, give estimated timeline
- Keep response under 100 words

Your response:"""

        return prompt

    def get_returns_prompt(self, context=""):
        """Prompt for returns/exchanges"""

        prompt = f"""You are a helpful customer service assistant.

Customer wants to return or exchange an item.

Return Policy:
- 30-day return window
- Item must be unworn with tags attached
- Free return shipping
- Refund processed within 5-7 business days

Instructions:
- Explain the return process clearly
- Be empathetic and helpful
- Mention the policy points above
- Offer to help initiate the return
- Keep response under 120 words

Your response:"""

        return prompt

    def get_refund_prompt(self):
        """Prompt for refund requests"""

        prompt = f"""You are a customer service assistant handling a refund request.

Refund Policy:
- Refunds processed within 5-7 business days
- Credited to original payment method
- Customer will receive email confirmation

Instructions:
- Be understanding and professional
- Explain the refund timeline
- Ask for order number if not provided
- Reassure the customer
- Keep response under 100 words

Your response:"""

        return prompt

    def get_account_help_prompt(self, issue_type="general"):
        """Prompt for account-related issues"""

        prompt = f"""You are a helpful customer service assistant.

Customer has an account-related issue: {issue_type}

Common Solutions:
- Password reset: Use "Forgot Password" link on login page
- Can't login: Check email/password, clear browser cache
- Update info: Go to Account Settings

Instructions:
- Provide clear, step-by-step help
- Be patient and supportive
- Offer escalation if issue persists
- Keep response under 100 words

Your response:"""

        return prompt

    def get_contact_info_prompt(self):
        """Prompt for contact information requests"""

        prompt = f"""You are a customer service assistant providing contact information.

Contact Information:
- Phone: 1-800-FASHION (1-800-327-4466)
- Email: support@fashionstore.com
- Hours: Monday-Friday 9AM-8PM EST, Saturday-Sunday 10AM-6PM EST
- Live Chat: Available on website during business hours

Instructions:
- Provide the contact information clearly
- Be friendly and helpful
- Mention availability/hours
- Keep response under 80 words

Your response:"""

        return prompt

    def get_general_faq_prompt(self, user_query, faq_context=""):
        """Prompt for general FAQ questions"""

        prompt = f"""You are a knowledgeable fashion store assistant.

Customer Question: "{user_query}"

Relevant Information:
{faq_context if faq_context else "Use general knowledge about online fashion retail."}

Instructions:
- Answer clearly and concisely
- Be friendly and professional
- If you don't know, admit it and offer to connect them with support
- Keep response under 100 words

Your response:"""

        return prompt

    def get_escalation_prompt(self, reason="customer request"):
        """Prompt for escalation messages"""

        responses = {
            "customer request": "Of course! I'm connecting you with one of our customer service representatives right now. They'll be with you shortly.",

            "frustration": "I apologize that I haven't been able to help effectively. Let me connect you with a customer service representative who can provide better assistance.",

            "complex issue": "This seems like a situation that would benefit from personalized attention. Let me connect you with our customer service team who can help resolve this.",

            "payment issue": "For your security, I'm connecting you with our customer service team who can access your account details and help with billing matters.",

            "account security": "For security reasons, I'll connect you with our support team who can verify your identity and help with account access."
        }

        return responses.get(reason, responses["customer request"])

# Create instance
prompt_templates = PromptTemplates()

# TEST PROMPT TEMPLATES

# Test 1: Product Search Prompt
mock_products = [
    {
        'name': 'Floral Summer Dress',
        'price': 45.99,
        'colors': ['Red', 'Blue', 'Pink'],
        'sizes': ['XS', 'S', 'M', 'L'],
        'description': 'Lightweight dress perfect for summer'
    },
    {
        'name': 'Casual Maxi Dress',
        'price': 52.99,
        'colors': ['Black', 'Navy'],
        'sizes': ['S', 'M', 'L', 'XL'],
        'description': 'Comfortable maxi dress for any occasion'
    }
]

product_prompt = prompt_templates.get_product_search_prompt(
    "Show me red dresses under $50",
    mock_products
)
print("Test 1:")
print(product_prompt)

# Test 2: Order Tracking Prompt
mock_order = {
    'order_id': 'ORD12345',
    'status': 'Shipped',
    'order_date': '2026-01-15',
    'tracking_number': 'TRK987654321'
}

order_prompt = prompt_templates.get_order_tracking_prompt(mock_order)
print(f"\nTest 2:")
print(order_prompt)

# Test 3: Returns Prompt
returns_prompt = prompt_templates.get_returns_prompt()
print(f"\nTest 3:")
print(returns_prompt)

# Test 4: No Products Found
no_products_prompt = prompt_templates.get_no_products_prompt(
    "Do you have purple polka dot pants?"
)
print(f"\nTest 4:")
print(no_products_prompt)

# Test 5: Escalation
escalation_msg = prompt_templates.get_escalation_prompt("customer request")
print(f"\nTest 5:")
print(escalation_msg)