# -*- coding: utf-8 -*-
"""response_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JC4EXJDaOYTM95h_sA3EVgs3qwYgDJn4
"""

# COMPONENT 3: LLM INTEGRATION WITH GEMINI (Response Generator)

class GeminiResponseGenerator:
    """
    Integrates Google Gemini API with the chatbot system
    """

    def __init__(self):
        """Initialize Gemini model"""
        self.model = genai.GenerativeModel('gemini-2.5-flash')
        self.classifier = IntentClassifier()
        self.prompts = PromptTemplates()

        # Mock data
        self.mock_products = [
            {
                'product_id': 'P001',
                'name': 'Classic Cotton T-Shirt',
                'price': 24.99,
                'colors': ['White', 'Black', 'Navy', 'Red'],
                'sizes': ['XS', 'S', 'M', 'L', 'XL'],
                'description': 'Soft 100% cotton t-shirt, perfect for everyday wear',
                'category': 'tops'
            },
            {
                'product_id': 'P002',
                'name': 'High-Waisted Denim Jeans',
                'price': 59.99,
                'colors': ['Light Blue', 'Dark Blue', 'Black'],
                'sizes': ['26', '28', '30', '32', '34'],
                'description': 'Comfortable stretch denim with classic styling',
                'category': 'bottoms'
            },
            {
                'product_id': 'P003',
                'name': 'Floral Summer Dress',
                'price': 45.99,
                'colors': ['Red Floral', 'Blue Floral', 'Pink Floral'],
                'sizes': ['XS', 'S', 'M', 'L'],
                'description': 'Lightweight dress perfect for warm weather',
                'category': 'dresses'
            },
            {
                'product_id': 'P004',
                'name': 'Leather Ankle Boots',
                'price': 89.99,
                'colors': ['Black', 'Brown', 'Tan'],
                'sizes': ['6', '7', '8', '9', '10'],
                'description': 'Genuine leather boots with comfortable insole',
                'category': 'shoes'
            },
            {
                'product_id': 'P005',
                'name': 'Cozy Knit Sweater',
                'price': 54.99,
                'colors': ['Cream', 'Grey', 'Burgundy', 'Navy'],
                'sizes': ['S', 'M', 'L', 'XL'],
                'description': 'Warm and soft acrylic blend sweater',
                'category': 'tops'
            }
        ]

        self.mock_orders = {
            'ORD001': {
                'order_id': 'ORD001',
                'status': 'Shipped',
                'order_date': '2026-01-10',
                'tracking_number': 'TRK123456789'
            },
            'ORD002': {
                'order_id': 'ORD002',
                'status': 'Processing',
                'order_date': '2026-01-18',
                'tracking_number': None
            }
        }

    def search_products(self, query):
        """Simple keyword-based product search"""
        query_lower = query.lower()
        matches = []

        for product in self.mock_products:
            if (any(color.lower() in query_lower for color in product['colors']) or
                product['category'] in query_lower or
                any(word in product['name'].lower() for word in query_lower.split())):
                matches.append(product)

        return matches[:3]

    def extract_order_id(self, query):
        """Extract order ID from query"""
        import re
        match = re.search(r'ORD\d+', query.upper())
        if match:
            return match.group()
        return None

    def call_gemini(self, prompt, max_retries=3):
        """
        Call Gemini API with retry logic

        Args:
            prompt: The prompt to send to Gemini
            max_retries: Number of retries on failure

        Returns:
            str: Generated response
        """
        for attempt in range(max_retries):
            try:
                response = self.model.generate_content(prompt)
                return response.text
            except Exception as e:
                print(f"Attempt {attempt + 1} failed: {str(e)}")
                if attempt == max_retries - 1:
                    return "I apologize, but I'm having trouble processing your request right now. Please try again in a moment."
                time.sleep(1)  # Wait before retry

    def generate_response(self, user_query):
        """
        Main function: Takes user query, returns bot response using Gemini

        Args:
            user_query (str): What the user asked

        Returns:
            dict: {
                'intent': detected intent,
                'confidence': confidence score,
                'response': bot's response from Gemini,
                'should_escalate': boolean,
                'prompt_used': the prompt sent to Gemini
            }
        """

        # Step 1: Classify intent
        intent, confidence = self.classifier.classify_with_confidence(user_query)

        # Step 2: Check if escalation needed
        if intent == 'escalation':
            return {
                'intent': intent,
                'confidence': confidence,
                'response': self.prompts.get_escalation_prompt("customer request"),
                'should_escalate': True,
                'prompt_used': None
            }

        # Step 3: Build appropriate prompt based on intent
        prompt = None

        if intent == 'product_search':
            products = self.search_products(user_query)
            prompt = self.prompts.get_product_search_prompt(user_query, products)

        elif intent == 'product_details':
            products = self.search_products(user_query)
            if products:
                # Create custom prompt for product details
                product = products[0]
                prompt = f"""You are a friendly fashion shopping assistant.

Customer asked: "{user_query}"

Product Information:
- Name: {product['name']}
- Price: ${product['price']}
- Available Colors: {', '.join(product['colors'])}
- Available Sizes: {', '.join(product['sizes'])}
- Description: {product['description']}

Instructions:
- Answer their specific question about this product
- Be enthusiastic and helpful
- Mention relevant details
- Keep response under 100 words
- End by asking if they'd like to know anything else

Your response:"""
            else:
                prompt = self.prompts.get_no_products_prompt(user_query)

        elif intent == 'order_tracking':
            order_id = self.extract_order_id(user_query)
            if order_id and order_id in self.mock_orders:
                order = self.mock_orders[order_id]
                prompt = self.prompts.get_order_tracking_prompt(order)
            else:
                prompt = """You are a helpful customer service assistant.

Customer is asking about order tracking but didn't provide a valid order number.

Instructions:
- Politely ask for their order number
- Mention it should look like ORD12345
- Be friendly and helpful
- Keep response under 60 words

Your response:"""

        elif intent == 'returns_exchanges':
            prompt = self.prompts.get_returns_prompt()

        elif intent == 'refund_request':
            prompt = self.prompts.get_refund_prompt()

        elif intent == 'account_management':
            prompt = self.prompts.get_account_help_prompt()

        elif intent == 'contact_info':
            prompt = self.prompts.get_contact_info_prompt()

        elif intent == 'payment_shipping':
            prompt = f"""You are a customer service assistant.

Customer asked: "{user_query}"

Information to provide:
- Payment methods: Visa, Mastercard, Amex, PayPal, Apple Pay
- Standard shipping (5-7 days): $5.99
- Express shipping (2-3 days): $12.99
- FREE standard shipping on orders over $50

Instructions:
- Answer their question clearly
- Be friendly and concise
- Keep response under 80 words

Your response:"""

        elif intent == 'size_guide':
            prompt = f"""You are a fashion shopping assistant helping with sizing.

Customer asked: "{user_query}"

Sizing Guidelines:
- Items run true to size
- If between sizes, size up
- Size chart available on each product page
- Measurements vary by product

Instructions:
- Help them find the right size
- Be encouraging and helpful
- Mention they can check specific product pages for detailed measurements
- Keep response under 100 words

Your response:"""

        else:  # general_faq
            prompt = self.prompts.get_general_faq_prompt(user_query)

        # Step 4: Call Gemini API
        if prompt:
            response_text = self.call_gemini(prompt)
        else:
            response_text = "I'm here to help! I can assist with finding products, tracking orders, returns, and more. What would you like to know?"

        return {
            'intent': intent,
            'confidence': confidence,
            'response': response_text,
            'should_escalate': False,
            'prompt_used': prompt
        }

# Create Gemini-powered chatbot
gemini_chatbot = GeminiResponseGenerator()

# TEST TRENDMATE

test_conversations = [
    "Show me red dresses",
    "Where is my order ORD001?",
    "I want to speak to a manager"
]

for i, query in enumerate(test_conversations, 1):
    print(f"CONVERSATION {i}")
    print(f"User: {query}")
    print()

    result = gemini_chatbot.generate_response(query)

    print(f"Detected Intent: {result['intent']} (confidence: {result['confidence']:.0%})")
    print(f"Escalate: {'Yes' if result['should_escalate'] else 'No'}")
    print()
    print(f"TrendMate Response:")
    print(result['response'])
    print()